# Generated by Django 4.2.19 on 2025-03-06 09:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('id_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('sub_location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('guardian_id', models.CharField(max_length=20)),
                ('guardian_first_name', models.CharField(max_length=255)),
                ('guardian_occupation', models.CharField(default='occupation', max_length=255)),
                ('guardian_income', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('guardian_kra', models.CharField(max_length=11, null=True)),
                ('guardian_contact', models.CharField(max_length=15, null=True)),
                ('institution_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('secondary', 'Secondary'), ('primary', 'Primary')], max_length=20)),
                ('institution_name_undergraduate', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_program_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_of_completion', models.CharField(blank=True, max_length=4, null=True)),
                ('current_year', models.CharField(blank=True, max_length=4, null=True)),
                ('amount_family_can_raise_undergraduate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_requested_undergraduate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('institution_name_primary', models.CharField(blank=True, max_length=255, null=True)),
                ('nemis_number_primary', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_family_can_raise_primary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_requested_primary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('institution_name_secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('nemis_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_family_can_raise_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_requested_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('personal_id', models.FileField(upload_to='documents/')),
                ('fee_structure', models.FileField(upload_to='documents/')),
                ('school_transcript', models.FileField(upload_to='documents/')),
                ('other_document', models.FileField(upload_to='documents/')),
                ('extracted_id_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BursaryFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fund', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('used_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='bursary', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('eligibility_criteria', models.TextField(default='')),
                ('application_deadline', models.DateField(default=datetime.date.today)),
                ('grade', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate')], default='undergraduate', max_length=15)),
                ('year_of_scholarship', models.PositiveIntegerField(default=2025)),
                ('documents_required', models.TextField(default='', help_text='List documents separated by commas')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(max_length=10)),
                ('email', models.EmailField(default='a@gmail.com', max_length=254)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_disbursed', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bursary_app.applications')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary_app.scheme'),
        ),
        migrations.AddField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary_app.studentextra'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='full name', max_length=255)),
                ('dob', models.DateField(default='2025-01-01')),
                ('id_number', models.CharField(default='youridnumber', max_length=20)),
                ('subcounty', models.CharField(default='subcounty', max_length=255)),
                ('sublocation', models.CharField(default='sublocation', max_length=255)),
                ('gender', models.CharField(default='female', max_length=10)),
                ('school_name', models.CharField(default='school name', max_length=255)),
                ('course', models.CharField(default='course name', max_length=255)),
                ('bank_name', models.CharField(default='bank name', max_length=255)),
                ('account_number', models.CharField(default='account number', max_length=20)),
                ('personal_id', models.FileField(blank=True, null=True, upload_to='applications/personal_ids/')),
                ('school_transcript', models.FileField(blank=True, null=True, upload_to='applications/school_transcripts/')),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='applications/fee_structures/')),
                ('proof_of_sickness', models.FileField(blank=True, null=True, upload_to='applications/proof_of_sickness/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bursary_app.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
