 # Generated by Django 4.2.19 on 2025-04-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='guardian_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Flagged', 'Flagged')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
